# Generated by Django 4.1.1 on 2023-01-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sender_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='message_color',
            field=models.CharField(default='gray', max_length=50, null=True),
        ),
    ]
